version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'

  redmine:
    image: redmine:5
    restart: always
    networks:
      - redmine
    volumes:
      - ./files:/usr/src/redmine/files
    ports:
      - 3000:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_PASSWORD=password'
      - 'REDMINE_DB_DATABASE=redmine'

volumes:
  postgres-data:

networks:
  redmine:
    driver: bridge
